services:
  web-app:
    build:
      context: .

    expose:
      - 8000
    volumes:
      - static:/static
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass

    env_file:
      - .env

    depends_on:
      - database

  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - 1337:80
    depends_on:
      - web-app

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass

volumes:
  static: