# Generated by Django 4.2.11 on 2024-04-19 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='orders',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
